// Solid Icons
import {
  faCode,
  faBook,
  faCogs,
  faCodeCompare,
  faFileCode,
  faLaptopCode,
  faTerminal,
  faSitemap,
  faListCheck,
  faDatabase,
  faServer,
  faMicrochip,
  faShareNodes,
  faGamepad,
  faCubes,
  faGlobe,
} from '@fortawesome/free-solid-svg-icons';

// Brand Icons
import {
  faSymfony,
  faUbuntu,
  faWindows,
  faLinux,
  faCss3,
  faNode,
  faGithub,
  faGitlab,
  faBitbucket,
  faUnity,
  faReact,
  faVuejs,
  faNodeJs,
  faNpm,
  faYarn,
} from '@fortawesome/free-brands-svg-icons';

import { IconRecord } from '../dataTypes/baseTypes';

export const iconMap: IconRecord = {
  code: faCode,
  codeCompare: faCodeCompare,
  fileCode: faFileCode,
  laptopCode: faLaptopCode,
  terminal: faTerminal,
  nodeJS: faNodeJs,
  css: faCss3,
  sitemap: faSitemap,
  github: faGithub,
  gitlab: faGitlab,
  bitbucket: faBitbucket,
  unity: faUnity,
  game: faGamepad,
  list: faListCheck,
  ubuntu: faUbuntu,
  node: faNode,
  book: faBook,
  cogs: faCogs,
  windows: faWindows,
  linux: faLinux,
  react: faReact,
  vue: faVuejs,
  database: faDatabase,
  server: faServer,
  technologie: faMicrochip,
  cubes: faCubes,
  symfony: faSymfony,
  share: faShareNodes,
  npm: faNpm,
  yarn: faYarn,
  globe: faGlobe,
};
